package entities;
// Generated 10 nov. 2015 12:53:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idClient;
     private String societe;
     private String telephone;
     private String email;
     private String addrLigne1;
     private String addrLigne2;
     private String ville;
     private String codePostal;
     private String motDePasse;
     private Set videos = new HashSet(0);

    public Client() {
    }

	
    public Client(String societe, String telephone, String email, String codePostal) {
        this.societe = societe;
        this.telephone = telephone;
        this.email = email;
        this.codePostal = codePostal;
    }
    public Client(String societe, String telephone, String email, String addrLigne1, String addrLigne2, String ville, String codePostal, String motDePasse, Set videos) {
       this.societe = societe;
       this.telephone = telephone;
       this.email = email;
       this.addrLigne1 = addrLigne1;
       this.addrLigne2 = addrLigne2;
       this.ville = ville;
       this.codePostal = codePostal;
       this.motDePasse = motDePasse;
       this.videos = videos;
    }
   
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public String getSociete() {
        return this.societe;
    }
    
    public void setSociete(String societe) {
        this.societe = societe;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddrLigne1() {
        return this.addrLigne1;
    }
    
    public void setAddrLigne1(String addrLigne1) {
        this.addrLigne1 = addrLigne1;
    }
    public String getAddrLigne2() {
        return this.addrLigne2;
    }
    
    public void setAddrLigne2(String addrLigne2) {
        this.addrLigne2 = addrLigne2;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getCodePostal() {
        return this.codePostal;
    }
    
    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }
    
    public String getMotDePasse() {
        return this.motDePasse;
    }
    
    public void setMotDePasse(String motDePasse) {
        this.motDePasse = motDePasse;
    }
    public Set getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set videos) {
        this.videos = videos;
    }




}


