package entities;
// Generated 10 nov. 2015 12:53:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compte generated by hbm2java
 */
public class Compte  implements java.io.Serializable {


     private Integer idCompte;
     private Typecompte typecompte;
     private String nom;
     private String prenom;
     private String login;
     private String password;
     private String salt;
     private Date creation;
     private Set videos = new HashSet(0);

    public Compte() {
    }

	
    public Compte(Typecompte typecompte, String nom, String prenom, String login, String password, String salt, Date creation) {
        this.typecompte = typecompte;
        this.nom = nom;
        this.prenom = prenom;
        this.login = login;
        this.password = password;
        this.salt = salt;
        this.creation = creation;
    }
    public Compte(Typecompte typecompte, String nom, String prenom, String login, String password, String salt, Date creation, Set videos) {
       this.typecompte = typecompte;
       this.nom = nom;
       this.prenom = prenom;
       this.login = login;
       this.password = password;
       this.salt = salt;
       this.creation = creation;
       this.videos = videos;
    }
   
    public Integer getIdCompte() {
        return this.idCompte;
    }
    
    public void setIdCompte(Integer idCompte) {
        this.idCompte = idCompte;
    }
    public Typecompte getTypecompte() {
        return this.typecompte;
    }
    
    public void setTypecompte(Typecompte typecompte) {
        this.typecompte = typecompte;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    public Date getCreation() {
        return this.creation;
    }
    
    public void setCreation(Date creation) {
        this.creation = creation;
    }
    public Set getVideos() {
        return this.videos;
    }
    
    public void setVideos(Set videos) {
        this.videos = videos;
    }




}


